from dataclasses import dataclass, asdict
from datetime import datetime
from typing import Dict

@dataclass
class SocialPost:
    """
    Represents a single, raw social media post generated by our simulator.
    """
    post_id: str
    platform: str # e.g., 'X-Twitter', 'Reddit'
    content: str
    author_id: str
    timestamp_utc: str # ISO 8601 format string

    def to_dict(self):
        """Converts the dataclass instance to a dictionary."""
        return asdict(self)

@dataclass
class EnrichedPost(SocialPost):
    """
    Represents a social media post after it has been processed and enriched
    by our AI analysis agent (Amazon Comprehend).
    """
    sentiment: str
    sentiment_score: Dict[str, float]
    key_phrases: list
    entities: list

    def to_dict(self):
        """Converts the dataclass instance to a dictionary."""
        return asdict(self)